require "csv"

ROOT_DIR = File.expand_path "#{File.dirname(__FILE__)}/../"

def pua?(four_hex_with_0x)
  case four_hex_with_0x
  when *%w{0xF860 0xF861 0xF862 0xF87A 0xF87E 0xF87F}
    true
  else
    false
  end
end

# Make pairs of string literals [[macjapanese, utf8], ...]
def make_pairs(use_pua = true)
  pairs = []
  # Control characters
  pairs += (0x00..0x1f).map do |ctrl|
    hex = ctrl.to_s(16).upcase
    ["\\x#{hex.rjust(2, "0")}", "\\u{#{hex.rjust(4, "0")}}"]
  end
  open("#{ROOT_DIR}/src/JAPANESE.txt") do |f|
    f.lines.each do |line|
      next if line =~ /^#/ # ignore comment
      next unless line =~ /^(0x.+)\t(0x.+)\t/ # capture
      macjp_hex, unicode_hex = $~.captures

      macjp = macjp_hex[2..-1].chars.each_slice(2).map{|hex| "\\x" + hex.join}.join

      unicode = unicode_hex.split("+").map{|hex|
        next "" if !use_pua && pua?(hex) # skip pua
        "\\u{#{hex[2..-1]}}"
      }.join

      pairs.push [macjp, unicode]
    end
  end
  pairs
end

# Make MacJapanese to UTF-8 table (with PUA)
open("#{ROOT_DIR}/lib/mac_japanese/mac_japanese_to_utf8_with_pua.rb", "w") do |f|
  f.puts <<-EOS
# This file was automatically generated by src/parse.rb.
# Cannot modify directly.
module MacJapanese
  MAC_JAPANESE_TO_UTF8_WITH_PUA = Hash[
    [
#{make_pairs.map{|m, u| %{      ["#{m}", "#{u}"]}}.join(",\n")}
    ].each{|m, u| m.force_encoding(Encoding::MacJapanese)}
  ]
end
EOS
end

# Make MacJapanese to UTF-8 table (without PUA)
open("#{ROOT_DIR}/lib/mac_japanese/mac_japanese_to_utf8_without_pua.rb", "w") do |f|
  f.puts <<-EOS
# This file was automatically generated by src/parse.rb.
# Cannot modify directly.
module MacJapanese
  MAC_JAPANESE_TO_UTF8_WITHOUT_PUA = Hash[
    [
#{make_pairs(false).map{|m, u| %{      ["#{m}", "#{u}"]}}.join(",\n")}
    ].each{|m, u| m.force_encoding(Encoding::MacJapanese)}
  ]
end
EOS
end

# Make UTF-8 to MacJapanese table
open("#{ROOT_DIR}/lib/mac_japanese/utf8_to_mac_japanese.rb", "w") do |f|
  f.puts <<-EOS
# This file was automatically generated by src/parse.rb.
# Cannot modify directly.
module MacJapanese
  UTF8_TO_MAC_JAPANESE = Hash[
    [
#{make_pairs.map{|m, u| %{      ["#{u}", "#{m}"]}}.join(",\n")}
    ].each{|u, m| m.force_encoding(Encoding::MacJapanese)}
  ]
end
EOS
end

# Make UTF-8 single character or decomposed characters regexp
decomposed_or_single_character_regexp = "/(" + make_pairs.map{|*, u| u}.select{|u| u.size > 8}.join("|") + "|.)/m"
open("#{ROOT_DIR}/lib/mac_japanese/decomposed_or_normal_character_regexp.rb", "w") do |f|
  f.puts <<-EOS
# This file was automatically generated by src/parse.rb.
# Cannot modify directly.
module MacJapanese
  DECOMPOSED_OR_NORMAL_CHARACTER_REGEXP = #{decomposed_or_single_character_regexp}
end
EOS
end
